site_name: UK Hackathons
site_url: https://hack.athon.uk/

nav:
  - Community:
    - Index: 'index.md'
    - Art: 'art/index.md'
    - Events:
      - Index: 'events/index.md'
      - List: 'events/list.md'
      - Family Tree: 'events/familytree.md'
      - HackSoc Lists:
        - Twitter: 'events/lists/twitter.md'
        - GitHub: 'events/lists/github.md'
  - Attend:
    - First Time: 'attend/firsttime.md'
    - What to Bring: 'attend/bring.md'
    - What to Make: 'attend/projects.md'
    - Resources: 'attend/resources.md'
    - Judging: 'attend/judging.md'
    - Transport: 'attend/transport.md'
    - Workshops:
      - Getting Started: 'attend/workshops.md'
      - Intro to Git: 'attend/workshops/introtogit.md'
    - Visas: 'attend/visas.md'
  - Organise:
    - Before The Event:
      - Getting Started: 'organise/before/gettingstarted.md'
      - Sponsorship: 'organise/before/sponsorship.md'
      - Finances: 'organise/before/finance.md'
      - Venue: 'organise/before/venue.md'
      - Catering: 'organise/before/catering.md'
      - Health and Safety: 'organise/before/health_and_safety.md'
      - Tech: 'organise/before/tech.md'
      - Opening and Closing Ceremonies: 'organise/before/av.md'
      - Judging Hacks: 'organise/before/judging.md'
      - Stash and Swag: 'organise/before/stash_and_swag.md'
      - Side Events: 'organise/before/side_events.md'
      - Visas: 'organise/before/visas.md'
    - During The Event:
      - Volunteers: 'organise/during/volunteers.md'
      - Mentors: 'organise/during/mentors.md'
      - Food: 'organise/during/food.md'
      - Submissions: 'organise/during/submissions.md'
      - Demos: 'organise/during/demos.md'
      #- Judging: 'organise/during/judging.md'
    - After The Event:
      - Photography: 'organise/after/photography.md'
      - Debrief: 'organise/after/debrief.md'
    - Help From The Community:
      # - Community: 'organise/help/community.md'
      - Hackathon Contacts: 'organise/help/poi.md'
      - Talking to Other Organisers: 'organise/help/communication.md'
      - Share Equipment: 'organise/help/share.md'
  - Sponsor: 'sponsor/index.md'
  - Help: 'volunteer/index.md'


theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'
  icon:
    logo: material/beaker
    repo: fontawesome/brands/git-alt

  features:
    - tabs
    - instant
  custom_dir: 'theme'

extra:
  social:
    - type: fab fa-facebook-f
      link: https://www.facebook.com/Hackathons-UK-104661511136163/
      alt: Hackathons UK Facebook
    - type: fab fa-twitter
      link: https://twitter.com/Hackathons_UK
      alt: Hackathons UK Twitter
    - type: fab fa-github-alt
      link: https://github.com/Hackathons-UK
      alt: Hackathons UK GitHub
    - type: fab fa-discord
      link: https://discord.gg/fpFWRQP
      alt: Hackathons UK Discord Server

  cal: https://pbs.twimg.com/profile_images/1240363609391316993/ZCYDAFPK_400x400.jpg

  hackathon_seasons:
    - name: Summer 2020
      past: false
      hackathons:
        - name: STEAM AiHack
          website: hack.innovationfest.co.uk/AiHack/
          location: Birmingham (Online)
          when: 27th-31st July 2020
          atendees: 100

    - name: Autumn 2020
      past: false
      hackathons:
        - name: HackTheMidlands 5.0
          background: /static/art/hackathon_tiles/htm_2020_background.png
          logo: /static/art/hackathon_tiles/htm_2020_logo.jpg
          website: https://hackthemidlands.com
          location: Birmingham (Venue TBC)
          when: 24th-25th October 2020 (TBC)
          atendees: 300
        - name: R.U. Hacking? 2020
          website: https://ruhacking.me/
          location: Reading University
          when: 24th-25th October 2020
          atendees: TBC
        - name: Hack Brunel 2.0
          website: https://hackbrunel.com/
          location: Brunel University London
          when: 31st October-1st November 2020
          atendees: 150
        - name: hackSheffield 6.0
          website: https://hacksheffield.com/
          location: University of Sheffield
          when: 7th-8th November 2020
          atendees: 200
        - name: DurHack 2020
          website: https://durhack.com/
          location: Durham University
          when: 14th-15th November 2020
          atendees: 425
        - name: HackNotts 2020
          website: https://www.hacknotts.com/
          location: University of Nottingham
          when: 28th-29th November 2020
          atendees: 200

    - name: Spring 2020
      past: true
      hackathons:
        - name: HackQuarantine
          website: https://hackquarantine.com/
          location: Online
          when: 23rd March-12th April 2020
          atendees: null
        - name: StacsHack 2020
          website: https://www.facebook.com/events/950732241970896/
          location: University of St Andrews
          when: 7th-8th March 2020
          atendees: null
        - name: HackMed
          website: http://hackmed.uk/
          location: University of Sheffield
          when: 14th-15th March 2020
          atendees: null
        - name: Hack the Burgh VI
          website: https://2020.hacktheburgh.com/
          location: University of Edinburgh
          when: 200
          atendees: 29th February-1st March 2020
        - name: IC Health Hack
          website: https://ichealthhack.org/
          location: Imperial College London
          when: null
          atendees: 29th February-1st March 2020
        - name: AI Hack 2020
          website: https://aihack.org/
          location: Imperial College London
          when: null
          atendees: 29th February-1st March 2020
        - name: Hack Keele
          website: https://www.facebook.com/hackkeele/posts/2571192316537510
          location: Keele University
          when: 29th February 2020
          atendees: null
        - name: ECSS CampusHack20
          website: https://www.eventbrite.co.uk/e/campushack20-tickets-91715420291
          location: University of Southampton
          when: 22nd-23rd February 2020
          atendees: null
        - name: RGUHack 2020
          website: https://rguhack.uk/
          location: Robert Gordon University, Aberdeen
          when: 22nd-23rd February 2020
          atendees: 80
        - name: HackSurrey v3.0
          website: https://hacksurrey.github.io/v3.0/
          location: University of Surrey
          when: 22nd-23rd February 2020
          atendees: 150
        - name: JunctionX Exeter
          website: https://junctionxexeter.com/
          location: University of Exeter
          when: 21st-23rd February 2020
          atendees: 100
        - name: CovHack2020
          website: https://covhack.org/
          location: Coventry University
          when: 15th-16th February 2020
          atendees: 150
        - name: Hack The South 2020
          website: https://hackthesouth.co.uk/
          location: University of Southampton
          when: 8th-9th February 2020
          atendees: 75
        - name: IC Hack 20
          website: https://ichack.org/
          location: Imperial College London
          when: 8th-9th February 2020
          atendees: 450
        - name: Quackathon 2020
          website: https://quackathon.com/
          location: University of Dundee
          when: 1st-2nd February 2020
          atendees: 100
        - name: Royal Hackaway v3
          website: https://royalhackaway.com/hackawayv3
          location: Royal Holloway, University of London
          when: 1st-2nd February 2020
          atendees: 75
        - name: ManMetHacks 2.0
          website: https://manmethacks.com/
          location: Manchester Metropolitan University
          when: 25th-26th January 2020
          atendees: 150
        - name: Hack Cambridge 101
          website: https://hackcambridge.com/
          location: University of Cambridge
          when: 18th-19th January 2020
          atendees: 300
        - name: StudentHackVIII
          website: https://www.studenthack.com/
          location: TBC
          when: 25th-26th April 2020
          atendees: 250

    - name: TBC
      hackathons:
        - name: DurHack:NextGen
          website: https://durhack.com/nextgen
          location: Durham University
          when: TBC
          atendees: 100 (U18 only!)



extra_css:
  - static/css/theme.css
  - static/css/home.css
  - static/css/hack-list.css


markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - macros
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
