site_name: UK Hackathons

nav:
  - Home: 'index.md'
  - Attending:
    - First time: 'attending/firsttime.md'
    - What to Bring: 'attending/bring.md'
    - What to make: 'attending/projects.md'
    - Judging: 'attending/judging.md'
    - Workshops: 'attending/workshops.md'
    - Transport: 'attending/transport.md' 
  - Events:
    - Index: 'events/index.md'
    - Family Tree: 'events/familytree.md'
  - Organise:
    - Getting Started: 'organise/gettingstarted.md'
    - Talking to Other Organisers: 'organise/communication.md'
    - Finances: 'organise/finance.md'
    - Catering: 'organise/catering.md'
    - Venue: 'organise/venue.md'
    - Tech: 'organise/tech.md'
    - Health And Safety: 'organise/has.md'
    - Opening and Closing Ceremonies: 'organise/av.md'
    - Side Events: 'organise/sideevents.md'
    - Share Equipment: 'organise/share.md'
    - Stash and Swag: 'organise/stashandswag.md'
    - Hackathon Contacts: 'organise/POI.md'
  - Sponsor: 'sponsor/index.md'
  - Volunteer: 'volunteer/index.md'
  - HackSoc Lists:
    - Twitter: 'lists/twitter.md'
    - Github: 'lists/github.md'



theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'
  logo:
    icon: computer
