site_name: UK Hackathons
site_url: https://hack.athon.uk/
site_description: |
  A wiki for helping hackers get into hackathons and organise them!

repo_url: https://github.com/athons/wiki

nav:

  - Home: 'index.md'
  - Attend:
    - First Time: 'attend/firsttime.md'
    - What to Bring: 'attend/bring.md'
    - What to Make: 'attend/projects.md'
    - Resources: 'attend/resources.md'
    - Judging: 'attend/judging.md'
    - Transport: 'attend/transport.md'
    - Workshops:
      - Getting Started: 'attend/workshops.md'
      - Intro to Git: 'attend/workshops/introtogit.md'
    - Visas: 'attend/visas.md'
  - Organise:
    - Online Events: 'organise/online/index.md'
    - Before The Event:
      - Getting Started: 'organise/before/gettingstarted.md'
      - Sponsorship: 'organise/before/sponsorship.md'
      - Finances: 'organise/before/finance.md'
      - Venue: 'organise/before/venue.md'
      - Catering: 'organise/before/catering.md'
      - Health and Safety: 'organise/before/health_and_safety.md'
      - Tech: 'organise/before/tech.md'
      - Opening and Closing Ceremonies: 'organise/before/av.md'
      - Judging Hacks: 'organise/before/judging.md'
      - Stash and Swag: 'organise/before/stash_and_swag.md'
      - Side Events: 'organise/before/side_events.md'
      - Visas: 'organise/before/visas.md'
    - During The Event:
      - Volunteers: 'organise/during/volunteers.md'
      - Mentors: 'organise/during/mentors.md'
      - Food: 'organise/during/food.md'
      - Submissions: 'organise/during/submissions.md'
      - Demos: 'organise/during/demos.md'
      #- Judging: 'organise/during/judging.md'
    - After The Event:
      - Photography: 'organise/after/photography.md'
      - Debrief: 'organise/after/debrief.md'
    - Help From The Community:
      # - Community: 'organise/help/community.md'
      - Hackathon Contacts: 'organise/help/poi.md'
      - Talking to Other Organisers: 'organise/help/communication.md'
      - Share Equipment: 'organise/help/share.md'
  - Sponsor:
    - Index: 'sponsor/index.md'
  - Volunteer:
    - Index: 'volunteer/index.md'
  - Community:
    - Events:
      - Index: 'events/index.md'
      - List: 'events/list.md'
      - Family Tree: 'events/familytree.md'
      - HackSoc Lists:
        - Twitter: 'events/lists/twitter.md'
        - GitHub: 'events/lists/github.md'


theme:
  name: 'material'
  palette:
    scheme: 'light'
    primary: 'pink'
    accent: 'pink'
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/git-alt

  features:
    - tabs
    - instant
  custom_dir: 'theme'

extra:
  social:
    - type: fab fa-github-alt
      link: https://github.com/athons
      alt: GitHub organisations
  placeholder_hackathon_background: /static/art/hackathon_tiles/stickers2.png

social:

extra_css:
  - static/css/theme.css
  - static/css/home.css
  - static/css/hack-list.css

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - macros:
      include_yaml:
        - events.yml
        - data/community.yml
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
